//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentListing
    {
        public int AgentListingId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> LisitngId { get; set; }
        public Nullable<int> OpenHouseId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
