//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenHouseSlot
    {
        public int OpenHouseId { get; set; }
        public Nullable<System.DateTime> OpenHouseDateBegin { get; set; }
        public Nullable<System.DateTime> OpenHouseDateEnd { get; set; }
        public Nullable<System.DateTime> OpenHouseCreatedDate { get; set; }
        public bool isActive { get; set; }
    }
}
